var myVar = "I am a var";         
let myLet = "I am a let";        
const myConst = "I am a const";  
let firstName = "Alice";
let greeting = `Hello, ${firstName}!`; 
let age = 25;
let price = 99.99;
let isLoggedIn = true;
let hasAccount = false;
let selectedItem = null;
let futureValue;
let user = { name: "Bob", role: "Developer", active: true };
let colors = ["red", "green", "blue"];
console.log("──── Variables ─────────────────────────────────");
console.log("myVar   :", myVar,   "| type:", typeof myVar);
console.log("myLet   :", myLet,   "| type:", typeof myLet);
console.log("myConst :", myConst, "| type:", typeof myConst);
console.log("\n──── Data Types ─────────────────────────────────");
console.log("firstName  :", firstName,  "| type:", typeof firstName);
console.log("age        :", age,        "| type:", typeof age);
console.log("price      :", price,      "| type:", typeof price);
console.log("isLoggedIn :", isLoggedIn, "| type:", typeof isLoggedIn);
console.log("hasAccount :", hasAccount, "| type:", typeof hasAccount);
console.log("selectedItem:", selectedItem, "| type:", typeof selectedItem);
console.log("futureValue:", futureValue,"| type:", typeof futureValue);
console.log("user       :", user,       "| type:", typeof user);
console.log("colors     :", colors,     "| type:", typeof colors);
console.log("\n──── Special Cases ──────────────────────────────");
console.log("typeof null  :", typeof null);   
console.log("typeof []    :", typeof []);     
console.log("Array.isArray([]):", Array.isArray(colors)); 
