const a = 15;
const b = 4;
console.log("──── Arithmetic Operators ───────────────────────");
console.log(`${a} + ${b} = ${a + b}`);   
console.log(`${a} - ${b} = ${a - b}`);   
console.log(`${a} * ${b} = ${a * b}`);   
console.log(`${a} / ${b} = ${a / b}`);   
console.log(`${a} % ${b} = ${a % b}`);   
console.log(`${a} ** ${b} = ${a ** b}`); 
console.log("\n──── Assignment Operators ────────────────────────");
let x = 10;
console.log("Initial x =", x);
x += 5;  console.log("x += 5  →", x);   
x -= 3;  console.log("x -= 3  →", x);   
x *= 2;  console.log("x *= 2  →", x);   
x /= 4;  console.log("x /= 4  →", x);   
x **= 2; console.log("x **= 2 →", x);   
x %= 10; console.log("x %= 10 →", x);   
console.log("\n──── Comparison Operators ────────────────────────");
console.log(`${a} == ${b}   →`, a == b);    
console.log(`${a} != ${b}   →`, a != b);    
console.log(`${a} > ${b}    →`, a > b);     
console.log(`${a} < ${b}    →`, a < b);     
console.log(`${a} >= 15     →`, a >= 15);   
console.log(`${b} <= 4      →`, b <= 4);    
console.log(`\n"5" == 5  (loose) →`, "5" == 5);   
console.log(`"5" === 5 (strict) →`, "5" === 5);   
console.log(`null == undefined  →`, null == undefined);   
console.log(`null === undefined →`, null === undefined);  
console.log("\n──── Logical Operators ───────────────────────────");
const p = a > 10;   
const q = b < 5;    
console.log(`a > 10 → ${p}`);
console.log(`b < 5  → ${q}`);
console.log(`(a > 10) && (b < 5) → ${p && q}`);  
console.log(`(a > 10) || (b > 5) → ${p || !q}`); 
console.log(`!(a > 10)           → ${!p}`);       
