console.log("──── Task 1: Fruits Array Manipulation ──────────");
let fruits = ["apple", "banana", "cherry"];
console.log("Initial array:", fruits);
fruits.push("mango");
console.log("After push('mango'):", fruits);
const removedFirst = fruits.shift();
console.log(`After shift() – removed '${removedFirst}':`, fruits);
fruits.unshift("strawberry");  
console.log("After unshift('strawberry'):", fruits);
const removedLast = fruits.pop();
console.log(`After pop() – removed '${removedLast}':`, fruits);
fruits.splice(1, 1);
console.log("After splice(1,1) – removed element at index 1:", fruits);
console.log("\n──── Task 2: Sum of Array Elements ──────────────");
const numbers = [10, 25, 5, 40, 15, 30, 8];
console.log("Numbers:", numbers);
const sumReduce = numbers.reduce((accumulator, current) => accumulator + current, 0);
console.log("Sum using reduce():", sumReduce);
let sumLoop = 0;
for (let num of numbers) {
  sumLoop += num;
}
console.log("Sum using for...of:", sumLoop);
console.log("\n──── Bonus: Array Methods Demo ───────────────────");
const scores = [88, 72, 95, 60, 45, 78, 91];
console.log("Scores:", scores);
const passing = scores.filter(score => score >= 75);
console.log("Passing (≥75):", passing);
const doubled = scores.map(score => score * 2);
console.log("Doubled:", doubled);
const firstHigh = scores.find(score => score > 90);
console.log("First score > 90:", firstHigh);
const sorted = [...scores].sort((a, b) => a - b);
console.log("Sorted ascending:", sorted);
console.log("includes 95:", scores.includes(95));
console.log("includes 100:", scores.includes(100));
console.log("indexOf 60:", scores.indexOf(60));
console.log("Every score > 40:", scores.every(s => s > 40));
console.log("Some score > 90:", scores.some(s => s > 90));
